### ISSUE TITLE
macOS:  cannot find -lprintf

### ISSUE THREAD

**Issue by KenjutsuGH** [ch32-riscv-ug/arduino_core_ch32_riscv_noneos#1]
Thank you for providing this repo.

I get the following error when I compile the **GPIO_Toggle** example:
`/Users/AAAAA/Library/Arduino15/packages/ch32-riscv-noneos/tools/riscv-none-embed-gcc/1.91/bin/../lib/gcc/riscv-none-embed/8.2.0/../../../../riscv-none-embed/bin/ld: cannot find -lprintf
`

**My setup:**
- macOS Sonoma 14.5 (23F79) M1
- Arduino IDE Version: 2.3.2  CLI Version: 0.35.3

![Screenshot 2024-05-23 at 16 31 48](https://github.com/ch32-riscv-ug/arduino_core_ch32_riscv_noneos/assets/11071556/f57ea71f-7087-4afa-afa7-9dcf4c3ce9d3)

**Comment by tanakamasayuki** [comment]
![wch_mac](https://github.com/ch32-riscv-ug/arduino_core_ch32_riscv_noneos/assets/10301363/3f5eb15a-5445-4d38-824e-264b13279d57)
Thanks for checking.
Mac was unchecked.
When I checked the wch original file, libprintf.a was not included.

I copied it from a Linux file in the same way as openwch.
https://github.com/ch32-riscv-ug/MounRiver_Studio_Community_miror/commit/4acf07f9ceb78a4710a6a9ea0497f1a6e52fe159

Please check again.
Requires deletion and addition of boards.

/Users/${username}/Library/Arduino15/package_ch32-riscv-noneos.json

If the above file is cached, it may not be reflected unless you delete it.

**Comment by KenjutsuGH** [comment]
Thank you, it now works perfectly
